Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:

  Avtoservice:
    category:
      model:                  Category
      page:                   true
      name:                   Категория|Категории
      components:
        listByCategory:
          filters:            [ category ]
        list:
        show:

    mark:
      model:                  Mark
      page:                   true
      name:                   Фирма|Фирмы
      components:
        list:
        show:

    product:
      parent:                 category
      page:                   true
      name:                   Оборудование|Оборудование
      components:
        listByCategory:
          filters:            [ category ]
        listByTag:
          filters:            [ tag ]
        listBySpecification:
          filters:            [ specification ]
        listByMark:
          filters:            [ mark ]
        listByNew:
        show:

    specification:
      model:                  Specification
      name:                   Характеристика|Характеристики
      components:
        list:

    specificationlink:
      model:                  Specificationlink
      name:                   Связь характеристики|Связи характеристик
      components:

    tag:
      model:                  Tag
      name:                   Тег|Теги
      page:                   true
      components:
        list:

  Feedback:              # arbitrary namespace, used in admin content menu
    contact:             # module's name
      components:        # module's components
        form:            # this module has a form action