generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Specification
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: specification
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        product_list:
          label: Оборудование
      list:
        display:
          - '=title'
          - product_list
          - measure
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - measure
      form:
        display:
          NONE: [title]
          Оборудование: [product_list]
          Others: [measure]
        class: SpecificationAdminForm
        fields: {  }
      edit: ~
      new: ~
