generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Taglink
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: taglink
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - tag_id
          - product_id
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - tag_id
          - product_id
      form:
        display:
          NONE: [tag_id, product_id]
        class: TaglinkAdminForm
        fields: {  }
      edit: ~
      new: ~
