generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Mark
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: mark
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=title'
          - image_id
          - products_list
          - description
          - sort
          - activity
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - prevdescription
          - description
          - image_id
          - sort
          - activity
      form:
        display:
          NONE: [title]
          Image: [image_id_form, image_id_view]
          Description: [description]
          Оборудование: [products_list]
          Others: [prevdescription, sort, activity]
        class: MarkAdminForm
        fields: {  }
      edit: ~
      new: ~
