default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - layout
    - main
    - markdown
    - eggplant/jquery-ui
    - fancybox/jquery.fancybox

  javascripts:
    - jquery-ui/js/jquery-1.10.2
    - jquery-ui/js/jquery-ui-1.10.4.custom.min
    - jquery.validate.min
    - additional-methods.min
    - messages_ru
    - 'http://www.google.com/recaptcha/api/js/recaptcha_ajax.js'
    - jquery.fancybox.pack
    - front
  has_layout:     true
  layout:         layout