default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - layout
    - main
    - markdown

  javascripts:
    - jquery-ui/js/jquery-1.10.2
    - jquery-ui/js/jquery-ui-1.10.4.custom.min
    - front

  has_layout:     true
  layout:         layout