generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Tag
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: tag
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=title'
          - taglinks_list
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
      form:
        display:
          NONE: [title]
          'Связи тегов': [taglinks_list]
        class: TagAdminForm
        fields: {  }
      edit: ~
      new: ~
