Category:
  columns:
    title:            { type: string(255), notnull: true }
    prevdescription:  { type: clob, extra: markdown }
    description:      { type: clob, extra: markdown }
    image_id:         { type: integer }
    sort:             { type: integer }
    activity:         { type: enum, values: [0, 1] }
    category_id:      { type: integer }
  relations:
    Category:
      foreignAlias:   Categories
    Image:
      class:      DmMedia
      local:      image_id
      onDelete:   RESTRICT

Mark:
  columns:
    title:             { type: string(255), notnull: true }
    prevdescription:   { type: clob, extra: markdown }
    description:       { type: clob, extra: markdown }
    image_id:          { type: integer }
    sort:              { type: integer }
    activity:          { type: enum, values: [0, 1] }
  relations:
    Image:
      class:      DmMedia
      local:      image_id
      onDelete:   RESTRICT

Product:
  columns:
    title:             { type: string(255), notnull: true }
    prevdescription:   { type: clob, extra: markdown }
    description:       { type: clob, extra: markdown }
    image_id:          { type: integer }
    sort:              { type: integer }
    activity:          { type: enum, values: [0, 1] }
    category_id:       { type: integer, notnull: true }
    mark_id:           { type: integer, notnull: true }
    cost:              { type: integer }
    isonslider:        { type: enum, values: [0, 1] }
    isnew:             { type: enum, values: [0, 1] }
  relations:
    Category:
      foreignAlias:   Products
    Mark:
      foreignAlias:   Products
    Image:
      class:      DmMedia
      local:      image_id
      onDelete:   RESTRICT

Specification:
  columns:
    title:             { type: string(255), notnull: true }
    measure:           { type: string(255), notnull: true }

Specificationlink:
  columns:
    specification_id:  { type: integer, notnull: true }
    product_id:        { type: integer, notnull: true }
    value:             { type: float, notnull: true }
  relations:
    Specification:
      foreignAlias:   Specificationlinks
    Product:
      foreignAlias:   Specificationlinks

Tag:
  columns:
    title:             { type: string(255), notnull: true }

Taglink:
  columns:
    tag_id:            { type: integer, notnull: true }
    product_id:        { type: integer, notnull: true }
  relations:
    Tag:
      foreignAlias:   Taglinks
    Product:
      foreignAlias:   Taglinks

Contact:
  actAs:              [ Timestampable ]
  columns:
    name:             { type: string(255), notnull: true }
    email:            { type: string(255), notnull: true }
    phone:            { type: string(255), notnull: true }
    topic:            { type: string(255) }
    body:             { type: clob }